import {
	Body,
	Container,
	Head,
	Heading,
	Html,
	Section,
	Text,
} from "@react-email/components";
import ReactMarkdown from "react-markdown";

type ItineraryEmailProps = {
	countryName: string;
	itinerary: string;
};

export function ItineraryEmail({
	countryName,
	itinerary,
}: ItineraryEmailProps) {
	return (
		<Html>
			<Head />
			<Body style={main}>
				<Container style={container}>
					<Heading style={h1}>Your {countryName} Travel Itinerary</Heading>
					<Section style={content}>
						<ReactMarkdown
							components={{
								h1: ({ children }) => (
									<Heading as="h1" style={markdownH1}>
										{children}
									</Heading>
								),
								h2: ({ children }) => (
									<Heading as="h2" style={markdownH2}>
										{children}
									</Heading>
								),
								h3: ({ children }) => (
									<Heading as="h3" style={markdownH3}>
										{children}
									</Heading>
								),
								p: ({ children }) => <Text style={paragraph}>{children}</Text>,
								strong: ({ children }) => (
									<strong style={bold}>{children}</strong>
								),
								ul: ({ children }) => <ul style={unorderedList}>{children}</ul>,
								ol: ({ children }) => <ol style={orderedList}>{children}</ol>,
								li: ({ children }) => <li style={listItem}>{children}</li>,
							}}
						>
							{itinerary}
						</ReactMarkdown>
					</Section>
					<Text style={footer}>
						Generated by Spot - Your travel planning companion
					</Text>
				</Container>
			</Body>
		</Html>
	);
}

const main = {
	fontFamily: 'Arial, "Helvetica Neue", Helvetica, sans-serif',
	backgroundColor: "#ffffff",
};

const container = {
	margin: "0 auto",
	padding: "20px 0 48px",
	maxWidth: "600px",
};

const h1 = {
	color: "#333333",
	fontSize: "24px",
	fontWeight: "bold",
	margin: "0 0 20px",
	textAlign: "left" as const,
};

const content = {
	backgroundColor: "#f5f5f5",
	borderRadius: "8px",
	padding: "20px",
	marginTop: "20px",
};

const markdownH1 = {
	color: "#333333",
	fontSize: "22px",
	fontWeight: "bold",
	margin: "20px 0 12px 0",
	textAlign: "left" as const,
};

const markdownH2 = {
	color: "#555555",
	fontSize: "18px",
	fontWeight: "bold",
	margin: "16px 0 10px 0",
	textAlign: "left" as const,
};

const markdownH3 = {
	color: "#666666",
	fontSize: "16px",
	fontWeight: "bold",
	margin: "12px 0 8px 0",
	textAlign: "left" as const,
};

const paragraph = {
	color: "#333333",
	fontSize: "14px",
	lineHeight: "1.6",
	margin: "8px 0",
	textAlign: "left" as const,
};

const bold = {
	fontWeight: "bold",
};

const unorderedList = {
	margin: "8px 0",
	paddingLeft: "20px",
};

const orderedList = {
	margin: "8px 0",
	paddingLeft: "20px",
};

const listItem = {
	margin: "4px 0",
	color: "#333333",
	fontSize: "14px",
	lineHeight: "1.6",
};

const footer = {
	color: "#666666",
	fontSize: "12px",
	marginTop: "20px",
	textAlign: "center" as const,
};
